### ISSUE TITLE
PyPi distribution issues

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#101]
The issue with our current folder structure is that, as organized in our Github repo, we actually have 4 packages:
- matrx
- docs
- examples
- matrx-visualizer

In our current (test) PyPi distribution of matrx only the first is present, resulting in an error when importing that package in Python: the module matrx-visualizer cannot be found. This makes sense as the complete matrx-visualizer folder is not present in PyPi matrx package. As such, what we (probably) should do is: 
- Split all four folders above in seperate repositories
- Create a PyPi package distribution for all four 
- Set the matrx-visualizer as a requirement for installing matrx (for now)

This does raise some issues:
- the matrx-visualizer will not be included anymore in the MATRX readthedocs. Solution could be to create a seperate read the docs for this. To make it easier for the user, the website styling can be copy-pasted to the readthedocs of MATRX, and the MATRX-visualizer. For instance, the header staying the same for matrx-software.com, matrx.readthedocs.com and matrx-visualizer.readthedocs.com, such that it looks like 1 website.

**Comment by thaije** [comment]
Also see issue #30, which is relevant for the use of MATRX as a Python package.

**Comment by jwaa** [comment]
I believe this is an issue because there is no namespace encapsulating both `matrx` and `matrx-visualizer`. So in addition to the option suggested by @thaije, we have the following options as well;

1. Seperate repos and builds for `matrx-visualizer` and `matrx` (original suggestion by @thaije)
2. Rename the current `matrx` folder to `matrx-core`, and encapsulate both `matrx-core` and `matrx-visualizer` in a new folder called `matrx`. Build from there.
3. Single repo, but seperate builds (if this is even possible with a single setup.py)

Option 1 is the cleanest. Though creates two seperate issue lists, adding to our overhead (also making it less transparent to new users where to ask question and new developers where to start coding).

Option 2 is the closest to what we desired. Though it creates another layer in our folder structure.

Option 3 is basically the first option but without the two repositories. Though it is unclear if this is even possible (I don't believe it is).

@thaije @mlstolk @wiardjorritsma What are your preferences?

Also, I do not think that there is an issue regarding the documentation of the MATRX-visualizer. We planned to seperate the docs from the code anyway, and nothing stops us to document two packages in one documentation repository and website.

**Comment by jwaa** [comment]
> Option 3 is basically the first option but without the two repositories. Though it is unclear if this is even possible (I don't believe it is).

Scratch that, option 3 is possible. See this link: https://packaging.python.org/guides/packaging-namespace-packages/

It basically says that we have a setup.py in `matrx` as well as `matrx-visualizer`. Then we can build them seperately from a single repository. It is important when doing a relase, to first build `matrx` and then `matrx-visualizer` as the latter imports the former. We can create a small build script that calls both setups if we go for this option.

**Comment by jwaa** [comment]
@mlstolk Is this still an issue? If so, please summarise why it is not anymore and close this issue. If it is still an issue, we need a vote on a solution.

**Comment by mlstolk** [comment]
No longer needed. matrx_visualizer is defined as a (sub)package in the pypi build, just as (the core) matrx is a package on its own.
Includes of matrx / matrx_visualizer packages work after the pip install in branch #82 . After a test by someone else and merging 82 into dev this issue can be closed,
