### ISSUE TITLE
Simplify image usages

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#114]
**Is your feature request related to a problem? Please describe.**
Currently we have two sources for images; the static folder and a user defined folder. The user folders have to be provided to MATRX by the user. But, they again have to do the same when selecting an image for a specific object. THis time the full relative path to the filename.

**Describe the solution you would like**
To simplify this, I suggest to ommit the need of providing a path at all when choosing an image for an object. Just search whether the file name is in one of the submitted folders (where user folders have preference over the MATRX static folder). The translation from filename to path can be done by the `WorldBuillder`.

**Describe alternatives you have considered**
N/A

**Additional context**
N/A

**Comment by thaije** [comment]
You mean if you have a user with a user-specified media folder structure such as this:
- /images
    - im1.jpg
    - /subfolder
        - im2.jpg

That the user can specify the first image simple with: `img_name="im1.jpg"`, but for the second image has to do: `img_name="subfolder/im2.jpg"`. The issue is that in the second case the subfolder part also has to be specified in the path? And that MATRX should automatically look through all subfolders for an image of name `im2.jpg`?

Although this saves the user some keystrokes, I think it might not become better or more transparent per se. Users might use subfolders to keep some structure, and might have images with duplicate names. E.g.: 
- /images
    - /team_blue
        - robot.jpg
    - /team_red
        - robot.jpg
In this case, the system would be unable to find the correct image.

Overall, I don't really see a situation where this would really benefit the user much, or improve the current functionality very much. Seeing the number of other features still open I would propose parking this issue untill specifically requested by a user :)  @jwaa feel free to re-open the issue if you think otherwise or if I misunderstood.
