### ISSUE TITLE
Object access through names instead of IDs

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#155]
**Is your feature request related to a problem? Please describe.**
Currently, every object and agent is accessed with its ID. However this is confusing as IDs are not consistent (see #132). This applies throughout MATRX, from the visualisation URL to building agents.

**Describe the solution you would like**
Use the `name` as ID, unless it is already taken. In that case output a message, and generate a unique ID and append it to the name.

**Describe alternatives you have considered**
N/A

**Additional context**
N/A

**Comment by jwaa** [comment]
This issue arrived mostly because people were having trouble locating things in an agent state. This is likely to be fixed with the new State object (see #156). This allows (among many things), the search for an object with a certain name. It returns one object of the name is unique, multiple if not.

I vote to close this issue, and make a more specific issue (e.g. finding objects in goals, loggers, etc. is difficult) if problems still occur. @thaije what do you think?

**Comment by thaije** [comment]
This has been fixed by just using the object name as the object ID. In the case of there being multiple objects with the same name, a counter is appended to the object ID. Example: three objects named "drone". The object IDs will then become "drone", "drone_1", "drone_2", etc.
The main advantage of this change is that the frontend agent links now are the same for consecutive runs of the same experiment, as the object IDs of these agents do not change. 

See here: https://github.com/matrx-software/matrx/commit/ec09192caf71a0b97f9904c40f1003c301278ae9#diff-64e5cead4ed2acde301f1d8243a6c53df97cf7b7b934c9acbd88247cfc3f28f1R326

@jwaa  do you think this is the correct method for fixing this, and the correct place? (the env_object)
