### ISSUE TITLE
Format readthedocs

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#166]
**Is your feature request related to a problem? Please describe.**
Given the completion of the documentation (see #165), the readthedocs pages should be reviewed on their formatting.

**Describe the solution you would like**
A nice and readable documentation structure that is consistent throughout.

**Describe alternatives you have considered**
N/A

**Additional context**
N/A

**Comment by thaije** [comment]
The documentation was completely broken, because of the renaming and reordering of our files. The documentation was still looking for `matrxs` and other non-existent files and folders. This has been fixed now. 

Writing down for future reference: 
See for example [this ](http://docs.matrx-software.com/en/latest/sections/actions.html) page. These classes were not clickable, because they refereed to non-existent files. 

I also discovered a peculiarity with the Sphinx documentation: 
See for example [this](http://docs.matrx-software.com/en/latest/sections/_generated_autodoc/matrx.world_builder.WorldBuilder.html#matrx.world_builder.WorldBuilder) page. The individual methods of the class are not clickable, if the class itself does not have a short description. 

Thus, the following will not work:
```
`Class Test():

def __init(self):
    """ All methods properly documented
    ....
    """
```

This will also not work:
```
`Class Test():
"""
A wonderful class description on the second line.
"""
def __init(self):
    """ Properly documented 
    ....
    """
```

This **does** work:
```
`Class Test():
""" A wonderful class description on the first line. 
More detailed explanation here.
"""
def __init(self):
    """ Properly documented 
    ....
    """
```

**Comment by thaije** [comment]
@jwaa Nice work with the documentation :) Pages like the ones for the [Move action](http://docs.matrx-software.com/en/latest/sections/_generated_autodoc/matrx.actions.move_actions.Move.html#matrx.actions.move_actions.Move) look great

**Comment by jwaa** [comment]
@thaije Do you have the time (and hours) to work on this issue for the next release?

**Comment by thaije** [comment]
@jwaa I do have some hours, however I am also tight on time coming weeks. My priority for now is fixing #154 , #182, #179. After those are done I can take a look at this, however I don't have a guarantee that it will be next week.

**Comment by jwaa** [comment]
Then I move this issue to the milestone of v1.2.0

**Comment by thaije** [comment]
Done
