### ISSUE TITLE
API request for abitrary object properties

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#177]
**Is your feature request related to a problem? Please describe.**
Currently the API supports the retrieval of full agent states, which gets filtered by our MATRX Visualizer. However, sometimes you don't want to deal with all that filtering when developing your own front-end. Then it helps if you can just ask what properties of all state objects you want.

**Describe the solution you would like**
An api call where you can signal which properties of all state objects you want to receive.

**Describe alternatives you have considered**
An alternative is a set of examples on how to filter on the state in several different languages (JS, C#, C/C++, Java, etc.). Though this is tedious for both us, MATRX developers, and the MATRX user.

**Additional context**
This request originates from the DASH project, that wishes to connect MATRX with a Unity3D front-end.

**Comment by thaije** [comment]
@jwaa If I understand correctly, the idea is you send an API request that fetches the state, but you specify specific properties to be returned? I was wondering, how big of an issue is this? For instance, do they only require 5% of the properties in the state? 

Such as the following API request: 
POST /get_latest_state_specific_properties 
With data:
{"object_properties": ["is_traversable", "is_movable", "visualize_size"]}

Returns:   
State, but for each object only the above properties if available, otherwise empty. 

Like that? 

I can see why you would want this, however, I am not sure if it should be programmed into the API or be left to the user to program. 
Pro's: 
- Filtering the state object is something almost every user will have to do that uses the API, as you almost never use every property
- It makes the API connection faster, as there is less data that has to be sent 
Con's: 
- It increases the required processing for the API server, as all the filtering of every API call now lies there. Every object in the state has to be gone through, and if not. 
- Which properties you want, is most likely dependent on the type of object. However, specifying this per object type increases the required processing even more. 

Overall, if we can find an efficient JSON array search library or algorithm, I see no reason why not to implement this. Otherwise, I would say let people implement it themselves. 


> An alternative is a set of examples on how to filter on the state in several different languages (JS, C#, C/C++, Java, etc.). Though this is tedious for both us, MATRX developers, and the MATRX user.

The state object returned is a JSON array, which is very command and easy parse. The only thing the user has to know is the structure of the state object, but that is something we should make a documentation / tutorial page on anyway. Otherwise, parsing a JSON array is something that is trivial in any modern programming language.

**Comment by jwaa** [comment]
I agree with the cons you mention. Users that build a new front end or run multiple clients will have to filter the state either way and potentually suffer from server side performance issues respectively. 

However, a pre-filter on the API side makes it easier to estimate what is in the json (since you can specify that yourself). I believe this is a great boon for ease-of-use.

I agree that people probably still have to filter the state. A solution could be your prosposal that you can not only provide the property name but also a value. Doing so, would set a filter that filters out all objects with that property and specific value. Such as the object type/inheritance.

I will see if I can add this as well, otherwise I make a new issue for it and assign it to the next milestone.

**Comment by jwaa** [comment]
Implemented. Can be used as follows (in python):

```python
data = {
    "properties": ["location", "isAgent"],
    "filters": {
        "class_inheritance": 'HumanAgentBrain'
    }
}

headers = {'content-type': 'application/json'}
r = requests.post(
    "http://localhost:3001/get_filtered_latest_state/['human2_79', 'human_78']",
    data=json.dumps(data), headers=headers,
)
```
This example works in `vis_test` and returns the `location` and `isAgent` boolean of all objects that inherit from `HumanAgentBrain` as perceived by the agents `human2_79` and `human_78` 

The return is json data with the agent ids as keys (in the example; `human2_79` and `human_78`) and their values are the requested properties with their respective values.
