### ISSUE TITLE
RemoveObject Action does not check for object existence

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#192]
**Describe the bug**
The RemoveObject action does not check whether the provided object_ID actually exists in the gridworld. 

**To Reproduce**
Remove an object, and print the is_possible result every tick of the already removed object.

**Expected behavior**
That the above is checked .

**Comment by jwaa** [comment]
@thaije Would this affect the intelligence of an agent? As in, that it would inadvertedly try to remove an object because it believes it is possible while it is not? Because, if the object does not exist how can the agent then decide to remove it? 

If the effect is minimal, let's fix it in the next milestone. If you foresee an impact we can fix it in one of upcoming hotfixes.
