### ISSUE TITLE
New state object incomplete for HumanAgent 

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#194]
**Describe the bug**
In the filter_observations function of the human agent, returning a State object as intended results in an error in the API: object is not serializable. This is because the State of human agents are not converted to a dict, as is done for the normal agent. 

**To Reproduce**
Instead of directly returning the `state` parameter of the `filter_observations` function in HumanAgent, create a new state object and return that: 
```
        new_human_state = State(own_id=self.agent_id)
        new_human_state.state_update(custom_state)
```` 

**Expected behavior**
The State object should be converted to a dictionary with the `to_dict()` function, as is done for the `AgentBrain.py`. 

**Solution** 
After a lot of digging, the cause seems to two fold: 
- In the HumanAgentBrain.py, the `_get_action()` function has not been properly updated for the new state object.[ These lines ](https://github.com/matrx-software/matrx/blob/master/matrx/agents/agent_brain.py#L530-L547) should be added to the [HumanAgentBrain.py](https://github.com/matrx-software/matrx/blob/master/matrx/agents/agent_types/human_agent.py#L142). Those lines include the `state.to_dict()` code that solves the JSON serializable error. 
- The second issue seems to be with the `_init_state()` functino of the `AgentBrain.py`. That function creates the initial `self.__state` object, which is a private object. However, the HumanAgentBrain.py also needs the self.__state object, which doesn't exist because it is private and can only be accessed from AgentBrain.py. As such, the `self.__state` needs to be changed to `self._state` everywhere in agentbrain and HumanAgentBrain.

**Comment by thaije** [comment]
@jwaa Can you check the above and see if it is plausible?

**Comment by jwaa** [comment]
So if I understand correctly this bug applies only to custom made HumanAgentBrain? I had no issues with our regular HumanAgentBrain.

I am not a fan of creating self.__state package private. As this would mean that it is too easily acessible for (Python novice) users. Instead the fix would be to copy all the additional lines for the State object in AgentBrain. Resulting in some repetitive coding, but this is what happens a lot anyway in HumanAgentBrain.

I can build thus fix, but I can only test it if I adjust the base class HumanAgentBrain. Since we don't have a test world with a custom human agent.

**Comment by jwaa** [comment]
You closed it already xD
