### ISSUE TITLE
Remove the customizable property functionality

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#212]
**Is your feature request related to a problem? Please describe.**
Several iterations went over the protection of properties, and at this point it is still far from perfect. Also, nobody uses it and if they do it is because it is buggy and that they have to.

**Describe the solution you would like**
Just remove the distinction between customizable and non-customizable properties and all that is related.

**Describe alternatives you have considered**
Perform yet another iteration of this concept, though I don't think this is warranted since nobody uses it.

**Additional context**
N/A

**Comment by thaije** [comment]
Removed in branch https://github.com/matrx-software/matrx/tree/212_remove_customizable_properties, and added deprecation warnings for usage of `customizable_properties` in the `WorldBuilder` and `EnvObject` so code of previous users doesn't break because the function parameter is unknown. 
Requires some further testing

**Comment by thaije** [comment]
Closed with https://github.com/matrx-software/matrx/releases/tag/v2.3.0
