### ISSUE TITLE
MATRX memory leak

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#217]
**Describe the bug**
When running MATRX for a while in the DASH project it keeps on using more RAM. At some point we were at 11gb of the 16gb available. We need to test this in some of our test world as well, to see if it 

**To Reproduce**
Run the DASH repository, but let's first test if it happens to any of our test worlds as well.

**Expected behavior**
It is fine that MATRX uses some memory, but to have it increase over time is pretty bad.

**Screenshots**
N/A

**Stacktrace**
N/A

**Additional context**
N/A

**Comment by jwaa** [comment]
@thaije Any clue where this comes from? I have the tendency to perform a detailed performance test on CPU & memory usage.

**Comment by thaije** [comment]
The cause seems to be in the MATRX API: https://github.com/matrx-software/matrx/blob/master/matrx/api/api.py#L27 
There, every state of every agent of every tick is saved. If you have a large grid world with many agents with high sense capabilities, this can lead to increasingly large amounts of RAM being used to save all these ticks.

**Comment by thaije** [comment]
A solution could be to only save 5 ticks into the past. Optionally saving older ticks to a database.
