### ISSUE TITLE
human in the state

### ISSUE THREAD

**Issue by Wouter1** [matrx-software/matrx#241]
**Describe the bug**
The human disappears from the agent state object after a few ticks.
First rounds you see 'human_0_team_0_346' in the state
The human is there the first 3 ticks or so and then suddenly not anymore.

**To Reproduce**
Run team of 2 bots and 1 human for short time.

**Expected behavior**
info about the human should remain in the state

**Additional context**
Experienced within the TuD version of BW4T

**Comment by jwaa** [comment]
@Wouter1 Is this with the agent moving or not? Just to rule out that the `HumanAgent` is not moving outside of the sensing range of the `Agent`.

**Comment by jwaa** [comment]
I added an additional context segment, as it might be specific to the BW4T task.

**Comment by Wouter1** [comment]
I'm not pressing buttons in the GUI, so I suppose only the agents are moving but not the human

The agents are moving so yes, it might be a range issue.

**Comment by Wouter1** [comment]
I thought that team would be always in view (in the state) so that I can discover their names etc for messaging them etc.

**Comment by Wouter1** [comment]
Did I misunderstand the function state.get_team_members ?

**Comment by jwaa** [comment]
> 
> 
> I'm not pressing buttons in the GUI, so I suppose only the agents are moving but not the human
> 
> The agents are moving so yes, it might be a range issue.

Can I assume this issue can thus be closed?

**Comment by jwaa** [comment]
Regarding the Team; agents need to be added to teams before this functionality works. Although the tracking and usage of teams is a fairly unused and unstable feature as of now.

The method `state.get_team_members` searches and returns the properties of agents that are part of a team, if any are indeed in sensing range (e.g., actually perceived). For this to work in a `State`, a team name should be provided when an agent is added to a `WorldBuilder` instance. See [the docs](http://docs.matrx-software.com/en/master/autoapi/matrx/world_builder/index.html#matrx.world_builder.WorldBuilder.add_agent) of [this method](https://github.com/matrx-software/matrx/blob/cc4e4f2a9e3562545d43c586f32078e1a466fed6/matrx/world_builder.py#L380). Agents with the same team name set in this way are deemed as part of the same team.

**Comment by Wouter1** [comment]
I thought to understand from that code that the bots are there all the time.  I assumed that the team name is '' since that's what I see in the state. And that that code was showing that the agents are available all the time. Why is there even a team name if there's no team... May I suggest to remove defunct code...

But, how about get_agents()? Are you saying that this is also defunct code? As that suggests exactly the same , that agent objects remain visible.

>See the docs 
The docs! I never found more docs on matrx. Can a link to this be put at the top of the wiki maybe?

**Comment by Wouter1** [comment]
If the other agents are not available in state, what's the way to get the other agent names? So that I can message them?

**Comment by jwaa** [comment]
>  I thought to understand from that code that the bots are there all the time.

I am not sure what you mean with this. Could you elaborate?

--------

You questions regarding the `State` and the team name functionality is moved to #242 to keep this issue on topic. I refer to #242 for my answers and followup questions regarding this. Same holds for your question on the docs; #243

**Comment by jwaa** [comment]
> 
> 
> If the other agents are not available in state, what's the way to get the other agent names? So that I can message them?

This is an issue encountered more often: If an agent does not see an object (e.g., another anget) but does need to interact with it (e.g., send a message), how does it get the object ID to do this if these IDs are generated on runtime?

The, very inconvenient but simplest workaround, is that you let the agent perceive other agents with infinite range by setting/altering its `SenseCapability` you provide when adding an agent. For example, to add an agent that always sees other agents:

```Python
from matrx.grid_world AgentBody
from matrx.agents import SenseCapability
import numpy as np

sense_capability = SenseCapability({AgentBody: np.inf})

```

@Wouter1 Since you are working with the BW4T code, on [this line](https://github.com/matrx-software/bw4t/blob/dev/builder.py#L139) the sense range for other agents is set. By changing the value on [this line](https://github.com/matrx-software/bw4t/blob/dd78e16fd61e8223f304cb4af098285ac9e11148/builder.py#L49) to infinite you achieve that all agents can see eachother all the time.

Now that we have set an agent to see all other agents, `State.get_agents()` method can be used to return all agents. This can for instance be done at the first time the `AgentBrain.filter_observations(...)` is called. In the same place all agents can also be removed from the `state` if in fact the agent should not use this info to decide its action on. For instance by either removing all agent objects or based on their distance with the help of the state's distance map: `state.get_distance_map()`.

I admit that this is very tedious and overly complex. As such we are thinking of using agent and object names instead of object IDs. This would require all names to be unique, but names are known before starting a `GridWorld` instance and thus names of agents or objects can simply passed to the constructor of an agent.

**Comment by jwaa** [comment]
I am closing this issue, as the main point seems to be resolved. I refer further discussion about the state and team name to #242, questions about the docs to #241, and for any more questions on how one can get the agent names to send messages I refer to #244.

**Comment by Wouter1** [comment]
Yes, thanks. Problem appeared to be the limited visibility range of other agents, which is apparently set by a parameter I did not know, plus that state.get_agents does not document this either. #244  is helpful and I added another method to get around this. Still I think state should get documentation as new users probably will run into this again.
