### ISSUE TITLE
change speed of individual agents

### ISSUE THREAD

**Issue by Wouter1** [matrx-software/matrx#248]
**What is your question?**
Can I change the speed of individual agents? How?

I just want to slow down an existing agent externally (eg in the builder program). Not modify the code of the agent. The agent should further work as usual, handling all the state.py objects as if nothing changed. It only sees the state change quicker than expected. Multiple messages may accumulate in its message box. It can see others jump around with bigger steps. 

I can see some complications for this too. For instance it may become difficult to see order of events as they happen. Doors may be opened and closed without the agent noticing it.

**Comment by jwaa** [comment]
@Wouter1 this can be done by setting the duration of an action. By providing this argument to any action, let's say a duration of `10`, causes the agent to not able perform an action for the subsequent 10 ticks. However, the `filter_observation` method will be called at every tick, just the `decide_on_action` method will not be called of that period. Also, all messages will still be send and received by the agent. 

See it as someone doing an action that takes time, while that person is doing the action it can still perceive the world and receive the messages from others. It can even send messages (e.g., shout) because that doesn't count as an action for MATRX. It just cannot act upon them since he/she is busy with an ongoing action.

**Comment by Wouter1** [comment]
@jwaa  Thanks, yes this is how we currently do it, indeed relying on that filter_observation will still be called. The details of how this works was clarified to me already in the other ticket.

The only issue here is that it is weird to 'ask' agents to set a duration of an action such that they will slow down themselves.
