### ISSUE TITLE
Significant simulation slow down since version 2.0.7

### ISSUE THREAD

**Issue by mlpeschl** [matrx-software/matrx#276]
**Describe the bug**
I have noticed that in versions 2.0.7 and 2.0.8 there is a steady and significant slow down in the simulation speed when repeatedly running the same world over and over again. In versions prior to 2.0.7 (I tested 2.0.3, 2.0.4, 2.0.5 and 2.0.6) I do notice a minor slow down at the start (first, say, 100 iterations) but then the speed seems to stabilize. 

**To Reproduce**
```python
from tqdm import tqdm
import matrx
from matrx import WorldBuilder
from matrx.agents import AgentBrain
from matrx.actions import MoveNorth
from matrx.actions.object_actions import DropObject

class IdleAgent(AgentBrain):
    def __init__(self):
        super().__init__()

    def initialize(self):
        pass

    def filter_observations(self, state):
        return state

    def decide_on_action(self, state):
        return MoveNorth.__name__, {'action_duration': 0}


def test_builder(run_matrx_api, run_matrx_visualizer, tick_speed):
    builder = WorldBuilder(shape=[9, 10], run_matrx_api=run_matrx_api, run_matrx_visualizer=run_matrx_visualizer,
                           visualization_bg_img='', tick_duration=tick_speed,
                          simulation_goal = 500)
    builder.add_room(top_left_location=[0, 0], width=9, height=10, name='Wall_Border')

    brain = IdleAgent()
    builder.add_agent([3, 1], brain, name='agent')


    return builder

def run_sim():
    builder = test_builder(run_matrx_api=False, run_matrx_visualizer=False, tick_speed=0)
    builder.startup()
    world = builder.get_world()
    world.run(api_info=builder.api_info)
    builder.stop()

for i in tqdm(range(1000)):
    run_sim()
```

**Expected behavior**
Please note that for this snippet I disabled the outputs in world_builder.py to get a more clear picture of the tqdm outputs. I would expect the speed to stay somewhat constant throughout the for loop. Furthermore, I noticed that the simulation runs at a much faster speed when removing the IdleAgent from the test_builder. I would expect this to not change too much, since the code of the idle agent should not require that much time to run.

**Screenshots**
-

**Stacktrace**
-

**Additional context**
I have been working on implementing some RL agents in matrx which need quite a lot of simulation steps (~5e6 steps at the moment) to learn. For that reason, I am trying to find out some ways to speed up the simulation which is where I noticed this behavior.

**Comment by jwaa** [comment]
@mlpeschl thank you for reporting this. It is indeed quite strange. I will look into it today and see if I can find the bottleneck.

**Comment by jwaa** [comment]
@mlpeschl I ran your example script (thank you for providing it!) under a profiler and plotted the time per iteration and the associated trend line. Below the results for v2.0.6 and v2.0.8, as it seems that this occurs as of v2.0.7 and onwards. Each result also includes a call graph from the final resulting `.pstats` file. As you can see I suffer from the same issue! The good news is that I probably found the error :)

@thaije; If I look at the callgraph for v2.0.8 it looks like the culprit is the `EnvObject._ensure_unique_obj_id` ([here](https://github.com/matrx-software/matrx/blob/93b00b6e74d2fdcd3bc986d18d044f7d8bf0999c/matrx/objects/env_object.py#L326)) in which 94.5% of the time is spend, which was more then 1 hour and 5 minutes out of the 1 hour and 9 minutes! If I understand it correctly the complexity of this method is `O(n)=n^n`, where `n` is the number of objects added whose list is never reset between world creations. Hence, when you create a 1.000 worlds, `n` gets quite large. If these are all the same worlds, you hit the worst-case complexity case.

The solution however is not that simple as resetting the list `added_obj_ids` as this is a static attribute of the entire MATRX package. Meaning that if you have two world builders, they both share the same list. Thus resetting this list might mess up the other builders. Perhaps we should relocate the creation of object ID's to a `WorldBuilder` instance? This is a tricky one though as we don't want to provide the ID as a parameter to `EnvObject`'s constructor, though we also cannot make a function in the builder that this constructor calls. As this either requires the instance of the `WorldBuilder` as a parameter or for it to be a class method creating import loops. 

@thaije Any other ideas?

# Test results

## v2.0.8
**Stats s/it**
- 10 worlds: mean: 0.222s, variance: 0.0025s
- 100 worlds: mean: 0.26s, variance: 0.0027s
- _**1.000 worlds: mean: 4.01s, variance: 0.0976s**_

**Plot s/it:**
![v2 0 8_1000_plot](https://user-images.githubusercontent.com/6059315/112684109-d8399380-8e72-11eb-9aac-6735e160d5e7.png)

**Call graph (1000 worlds):**
![v2 0 8_1000_callgraph](https://user-images.githubusercontent.com/6059315/112684187-f1dadb00-8e72-11eb-965c-be473723e921.png)

## v2.0.6
**Stats s/it**
- 10 worlds: mean: 0.208s, variance: 0.0116s
- 100 worlds: mean: 0.193s, variance: 0.0007s
- 1.000 worlds: mean: 0.198s, variance: 0.0004s

**Plot s/it:**
![v2 0 6_1000_plot](https://user-images.githubusercontent.com/6059315/112673246-ccdf6b80-8e64-11eb-8c8e-2d20072c0e0e.png)

**Call graph (1000 worlds):**
![v2 0 6_1000_callgraph](https://user-images.githubusercontent.com/6059315/112673400-f5fffc00-8e64-11eb-9a64-da3a7319e69c.png)


# Code snippet used
```Python
import contextlib
import os
import time

import pkg_resources
from tqdm import tqdm
from matrx import WorldBuilder
from matrx.agents import AgentBrain
from matrx.actions import MoveNorth
from matrx import __version__ as matrx_version

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import cProfile
import pstats


class IdleAgent(AgentBrain):
    def __init__(self):
        super().__init__()

    def initialize(self):
        pass

    def filter_observations(self, state):
        return state

    def decide_on_action(self, state):
        return MoveNorth.__name__, {'action_duration': 0}


def test_builder(run_matrx_api, run_matrx_visualizer, tick_speed):
    builder = WorldBuilder(shape=[9, 10], run_matrx_api=run_matrx_api, run_matrx_visualizer=run_matrx_visualizer,
                           visualization_bg_img='', tick_duration=tick_speed,
                           simulation_goal=500)
    builder.add_room(top_left_location=[0, 0], width=9, height=10, name='Wall_Border')

    brain = IdleAgent()
    builder.add_agent([3, 1], brain, name='agent')

    return builder


def run_sim():

    with open(os.devnull, "w") as f, contextlib.redirect_stdout(f):
        builder = test_builder(run_matrx_api=False, run_matrx_visualizer=False, tick_speed=0)
        builder.startup()
        world = builder.get_world()
        world.run(api_info=builder.api_info)
        builder.stop()


def repeat_sim(n_sims, matrx_v):
    ts = []

    # Start profiler
    pr = cProfile.Profile()
    pr.enable()

    # Run worlds
    for i in tqdm(range(n_sims)):
        t = time.time()
        run_sim()
        ts.append(time.time() - t)

    # Disable profiler and store stats
    pr.disable()
    pstats.Stats(pr).dump_stats(f"{matrix_v}\\v{matrx_v}_{n_sims}.pstats")

    return ts


if __name__ == "__main__":
    # Create version folder
    matrix_v = pkg_resources.get_distribution("matrx").version
    os.mkdir(matrix_v)

    # Run 10
    ts = repeat_sim(10, matrix_v)
    mean = sum(ts)/len(ts)
    stdev = np.sqrt(sum([(t - mean)**2 for t in ts])) / len(ts)
    print(f"\nmean: {np.round(mean, 3)}s, variance: {np.round(stdev, 4)}s")

    # Run 100
    ts = repeat_sim(100, matrix_v)
    mean = sum(ts)/len(ts)
    stdev = np.sqrt(sum([(t - mean)**2 for t in ts])) / len(ts)
    print(f"\nmean: {np.round(mean, 3)}s, variance: {np.round(stdev, 4)}s")

    # Run 1000
    ts = repeat_sim(1000, matrix_v)
    mean = sum(ts)/len(ts)
    stdev = np.sqrt(sum([(t - mean)**2 for t in ts])) / len(ts)
    print(f"\nmean: {np.round(mean, 3)}s, variance: {np.round(stdev, 4)}s")

    # Plot graph
    data = pd.DataFrame({"iteration": range(len(ts)), "seconds": ts})
    average = float(data[['seconds']].mean(axis=0))
    sns.regplot(x='iteration', y='seconds', data=data, fit_reg=True, ci=95, line_kws={"color": "r"}, order=2)
    plt.title(f"MATRX v{matrix_v} - Seconds per Iteration (mean:{np.round(average, 3)}s, stdev:{np.round(stdev, 4)})s")
    plt.savefig(f"{matrix_v}\\v{matrix_v}_{len(ts)}_plot.png")
    plt.show()
```

**Comment by thaije** [comment]
Thanks for catching this bug and the nice analysis! I had not expected this little for loop to have that much of an impact as it did, and honestly also forgot that  running  worlds consecutively  all object_ids ever gathered over all these worlds would be gathered inside the `added_obj_ids` list. 

I gave it some thought and in the end came up with a fix for the ugly for loop, see below. Instead of keeping track of all the obj_ids ever added as we did before, we now keep track of how often we added an object  as indexed by the object name  (or atleast the obj_name as received by this function after some preprocessing in the constructor). 

In the example code in the issue, in Matrx v2.0.8 the  `added_obj_ids` variable  is equal in length to the number of total objects (1000 runs * ~50 objects in the example = 50.000 items), and `_ensure_unique_obj_ID` runs with O(n)=n^n. 

In the code below `obj_indices` is equal in length to the total number of unique obj_names (in the example after 1 run 2, and after 1000 runs still only 2), which is much smaller as most objects are duplicates (walls, blocks, etc.) with an identical name. Especially with running 1000 worlds consecutively, the objects (names) in those worlds are mot likely largely the same for those instances, or the world might be exactly the same. Also it runs with O(n) = n I think? Atleast much faster. I think we don't even need to reset the `obj_indices` variable between worlds for optimization sake. Maybe only as it might be more intuitive that every world has object_ids that start from 0, instead of world 800 having walls with IDs starting at wall_40001.

@jwaa what do you think? And can you do a comparison profiling with the fix? :) 

```
# keeps track of all obj_ids added 
obj_indices = {}

def gen_unique_id(obj_name):
	""" Make sure every obj ID is unique by adding an increasing count to objects with duplicate names.
    Example: three objects named "drone". The object IDs will then become "drone", "drone_1", "drone_2", etc."""

	# check if an object by this name was already added, and gen a unique ID if so 
	if obj_name in obj_indices.keys():

		# get the latest index we are at for this obj, e.g. wall #10
		n = obj_indices[obj_name] 
		obj_indices[obj_name] += 1

		# double check that the new id is unique or increment until it is 
		while f"{obj_name}_{n}" in obj_indices.keys():
			n = obj_indices[obj_name]
			obj_indices[obj_name] += 1

		# set the new id 
		obj_id = f"{obj_name}_{n}"

	# otherwise obj name can be used as obj id 
	else:
		obj_indices[obj_id] = 1
		obj_id = obj_name 

	return obj_id
```

**Comment by thaije** [comment]
Instead of `obj_indices` is `objects_counters` a better name btw.

**Comment by jwaa** [comment]
Thanks for the solution! "The devil of optimization is in the details of a loop." ;)

I was also thinking about a solution where we use a more efficient way of storing it. So it seems to make sense. Besides the counter-intuitiveness of the ID's we do face the issue of each world also changing the agent URLs for the visualization right if they are similarly named? 

Previously the URLs were cumbersome but atleast constant over different worlds as long as there was no stochasticity in its creation. Now however, that is not the case I believe. As each world run causes every object to have a different ID if the name is reused.

Resetting the list between world creation could fix this, but brings all the other issues with it.

Will try and rerun the analysis script this afternoon/evening :)

**Comment by jwaa** [comment]
Took a bit longer then expected (since I forgot). Below the results. The complexity is indeed O(n)=n, also reflected in the graph below. So your fix @thaije indeed improves things! 

# Test Results

## v2.0.9a ([update](https://github.com/matrx-software/matrx/issues/276#issuecomment-808607383))

**Stats s/it:**

- 10 worlds: 0.255s, variance: 0.0087s
- 100 worlds: 0.231s, variance: 0.0011s
- 1.000 worlds: 0.233s, variance: 0.0003s

**Plot s/it**
![v2 0 8_1000_plot](https://user-images.githubusercontent.com/6059315/113111233-45994b80-9208-11eb-85da-b7ba3b063726.png)


**Call graph 1.000 worlds**
![v2 0 8_1000_callgraph](https://user-images.githubusercontent.com/6059315/113111251-49c56900-9208-11eb-98d8-165fbfbfa591.png)

**Comment by thaije** [comment]
@jwaa I implemented a fix that is fast + resets the IDs for every new MATRX world without any static methods or other hacks so the frontend URL doesn't change all the time. See here: https://github.com/matrx-software/matrx/pull/278. Can you check it out?
