### ISSUE TITLE
Allow sending human message while busy

### ISSUE THREAD

**Issue by rsverhagen94** [matrx-software/matrx#326]
**What is your question?**
Is there a quick way to still allow humans to send messages in the chat while their agent is busy performing an action taking multiple ticks? Right now it waits with sending a message until the visualize_when_busy icon disappears aka when the action is finished.

**To what is your question related?**
- [ ] I am not sure if I should use MATRX.
- [ ] I have a question about the idea behind MATRX.
- [X] I don't know how to do something with MATRX.
- [ ] I don't know where to find something.
- [ ] I think I found a bug, but I am not sure.
- [ ] I want to contribute, but don't know where to start.
- [ ] Something else.

**Comment by jwaa** [comment]
Thanks for the question @rsverhagen94 .

@thaije is the issue here a blocking animation in the frontend? 

If not I am afraid it is a more fundamental issue in the agent being blocked until the action is done. Messages are handled when the agent is ready for it. @rsverhagen94 it might be a bit inconvenient, would it be an option for you to separate the long action in a bunch of smaller ones with just a wait time to end with the actual action? It does require some inconvenient tracking though... Otherwise you have to wait until we changed this in a future version.

@thaije other suggestions?

**Comment by thaije** [comment]
Yes the issue is that if an agent is busy, its messages will not be read. 
In the code messages are fetched [here](https://github.com/matrx-software/matrx/blob/75bdf8d8dbe7b70a6768031b40b206458d706b07/matrx/grid_world.py#L707), which is not called when an agent is busy. 

This was implemented with the idea that if an agent is busy and thus never gets to the `decide_on_action` no message will be sent. However, it makes sense that an user would like to send messages via the chat even when it's agent is busy. 

As such, I would propose we just change the message fetching code to be always executed, even when an agent is busy. Aside from that I see no clear solution to this. I can push a new version tomorrow with this fix if needed.

**Comment by rsverhagen94** [comment]
Thanks a lot for the replies @jwaa and @thaije. I would very much appreciate your proposed fix @thaije.

**Comment by rsverhagen94** [comment]
@thaije thanks for the update. However, what happens now is that while being busy the message gets send, but the human aborts the action it was busy with.

**Comment by thaije** [comment]
Hey Ruben, I double checked and was unable to encounter the issue you described. [Here](https://github.com/matrx-software/matrx/tree/326_message_while_busy) is the branch with which I tested. For testing I added `action_kwargs['action_duration'] = 50` for all actions of a human agent. Any action such as moving the human around then takes 5 seconds to complete a single move, and sending a message in the chat in the mean team is sent successfully (confirmed by arriving in chat) without aborting the action (move is executed) or cutting the `action_duration` short. 

Do you have some more details on how to reproduce the error?
